use anyhow::Result;
use crate::theme::Theme;
use crate::utils::{lighten_color, darken_color};

pub fn generate(theme: &Theme) -> Result<String> {
    let mut output = String::new();
    
    output.push_str("# Btop theme: ");
    output.push_str(&theme.name);
    output.push_str("\n");
    output.push_str("# Generated by themectl\n");
    output.push_str("# Colors should be in 6 or 2 character hexadecimal or single spaced RGB decimal: \"#RRGGBB\", \"#BW\" or \"0-255 0-255 0-255\"\n\n");
    
    // Main colors
    output.push_str("[main_bg] = \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\"\n");
    
    output.push_str("[main_fg] = \"");
    output.push_str(&theme.colors.fg);
    output.push_str("\"\n");
    
    output.push_str("[title] = \"");
    output.push_str(&theme.colors.accent);
    output.push_str("\"\n");
    
    output.push_str("[hi_fg] = \"");
    output.push_str(&theme.colors.yellow);
    output.push_str("\"\n");
    
    output.push_str("[selected_bg] = \"");
    output.push_str(&theme.colors.accent);
    output.push_str("\"\n");
    
    output.push_str("[selected_fg] = \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\"\n");
    
    // Inactive foreground - use a dimmed version of fg
    output.push_str("[inactive_fg] = \"");
    if let Some(dimmed) = darken_color(&theme.colors.fg, 0.4) {
        output.push_str(&dimmed);
    } else {
        output.push_str(&theme.colors.fg);
    }
    output.push_str("\"\n");
    
    output.push_str("[graph_text] = \"");
    if let Some(gray) = theme.get_color("gray") {
        output.push_str(gray);
    } else {
        output.push_str(&theme.colors.fg);
    }
    output.push_str("\"\n");
    
    output.push_str("[meter_bg] = \"");
    if let Some(darkened) = darken_color(&theme.colors.bg, 0.2) {
        output.push_str(&darkened);
    } else {
        output.push_str(&theme.colors.bg);
    }
    output.push_str("\"\n");
    
    output.push_str("[proc_misc] = \"");
    if let Some(purple) = theme.get_color("purple") {
        output.push_str(purple);
    } else {
        output.push_str(&theme.colors.magenta);
    }
    output.push_str("\"\n");
    
    // Box border colors - use accent colors
    output.push_str("[cpu_box] = \"");
    output.push_str(&theme.colors.blue);
    output.push_str("\"\n");
    
    output.push_str("[mem_box] = \"");
    output.push_str(&theme.colors.green);
    output.push_str("\"\n");
    
    output.push_str("[net_box] = \"");
    output.push_str(&theme.colors.cyan);
    output.push_str("\"\n");
    
    output.push_str("[proc_box] = \"");
    output.push_str(&theme.colors.accent);
    output.push_str("\"\n");
    
    output.push_str("[div_line] = \"");
    if let Some(gray) = theme.get_color("gray") {
        output.push_str(gray);
    } else if let Some(dimmed) = darken_color(&theme.colors.fg, 0.5) {
        output.push_str(&dimmed);
    } else {
        output.push_str(&theme.colors.fg);
    }
    output.push_str("\"\n\n");
    
    // Temperature gradient (green -> yellow -> red)
    output.push_str("# Temperature gradient\n");
    output.push_str("[temp_start] = \"");
    output.push_str(&theme.colors.green);
    output.push_str("\"\n");
    output.push_str("[temp_mid] = \"");
    output.push_str(&theme.colors.yellow);
    output.push_str("\"\n");
    output.push_str("[temp_end] = \"");
    output.push_str(&theme.colors.red);
    output.push_str("\"\n\n");
    
    // CPU usage gradient (green -> yellow -> red)
    output.push_str("# CPU usage gradient\n");
    output.push_str("[cpu_start] = \"");
    output.push_str(&theme.colors.green);
    output.push_str("\"\n");
    output.push_str("[cpu_mid] = \"");
    output.push_str(&theme.colors.yellow);
    output.push_str("\"\n");
    output.push_str("[cpu_end] = \"");
    output.push_str(&theme.colors.red);
    output.push_str("\"\n\n");
    
    // Free memory/disk gradient (green)
    output.push_str("# Free memory/disk gradient\n");
    output.push_str("[free_start] = \"");
    output.push_str(&theme.colors.green);
    output.push_str("\"\n");
    output.push_str("[free_mid] = \"");
    if let Some(lightened) = lighten_color(&theme.colors.green, 0.2) {
        output.push_str(&lightened);
    } else {
        output.push_str(&theme.colors.green);
    }
    output.push_str("\"\n");
    output.push_str("[free_end] = \"");
    output.push_str(&theme.colors.green);
    output.push_str("\"\n\n");
    
    // Cached memory gradient (cyan)
    output.push_str("# Cached memory gradient\n");
    output.push_str("[cached_start] = \"");
    output.push_str(&theme.colors.cyan);
    output.push_str("\"\n");
    output.push_str("[cached_mid] = \"");
    if let Some(lightened) = lighten_color(&theme.colors.cyan, 0.2) {
        output.push_str(&lightened);
    } else {
        output.push_str(&theme.colors.cyan);
    }
    output.push_str("\"\n");
    output.push_str("[cached_end] = \"");
    output.push_str(&theme.colors.cyan);
    output.push_str("\"\n\n");
    
    // Available memory gradient (blue)
    output.push_str("# Available memory gradient\n");
    output.push_str("[available_start] = \"");
    output.push_str(&theme.colors.blue);
    output.push_str("\"\n");
    output.push_str("[available_mid] = \"");
    if let Some(lightened) = lighten_color(&theme.colors.blue, 0.2) {
        output.push_str(&lightened);
    } else {
        output.push_str(&theme.colors.blue);
    }
    output.push_str("\"\n");
    output.push_str("[available_end] = \"");
    output.push_str(&theme.colors.blue);
    output.push_str("\"\n\n");
    
    // Used memory/disk gradient (red -> yellow -> green, inverted for usage)
    output.push_str("# Used memory/disk gradient\n");
    output.push_str("[used_start] = \"");
    output.push_str(&theme.colors.green);
    output.push_str("\"\n");
    output.push_str("[used_mid] = \"");
    output.push_str(&theme.colors.yellow);
    output.push_str("\"\n");
    output.push_str("[used_end] = \"");
    output.push_str(&theme.colors.red);
    output.push_str("\"\n\n");
    
    // Download gradient (green/cyan)
    output.push_str("# Download gradient\n");
    output.push_str("[download_start] = \"");
    output.push_str(&theme.colors.green);
    output.push_str("\"\n");
    output.push_str("[download_mid] = \"");
    output.push_str(&theme.colors.cyan);
    output.push_str("\"\n");
    output.push_str("[download_end] = \"");
    if let Some(lightened) = lighten_color(&theme.colors.cyan, 0.2) {
        output.push_str(&lightened);
    } else {
        output.push_str(&theme.colors.cyan);
    }
    output.push_str("\"\n\n");
    
    // Upload gradient (blue/magenta)
    output.push_str("# Upload gradient\n");
    output.push_str("[upload_start] = \"");
    output.push_str(&theme.colors.blue);
    output.push_str("\"\n");
    output.push_str("[upload_mid] = \"");
    output.push_str(&theme.colors.magenta);
    output.push_str("\"\n");
    output.push_str("[upload_end] = \"");
    if let Some(lightened) = lighten_color(&theme.colors.magenta, 0.2) {
        output.push_str(&lightened);
    } else {
        output.push_str(&theme.colors.magenta);
    }
    output.push_str("\"\n\n");
    
    // Process resource usage gradient (accent color)
    output.push_str("# Process resource usage gradient\n");
    output.push_str("[process_start] = \"");
    output.push_str(&theme.colors.accent);
    output.push_str("\"\n");
    output.push_str("[process_mid] = \"");
    if let Some(lightened) = lighten_color(&theme.colors.accent, 0.2) {
        output.push_str(&lightened);
    } else {
        output.push_str(&theme.colors.accent);
    }
    output.push_str("\"\n");
    output.push_str("[process_end] = \"");
    if let Some(lightened) = lighten_color(&theme.colors.accent, 0.4) {
        output.push_str(&lightened);
    } else {
        output.push_str(&theme.colors.accent);
    }
    output.push_str("\"\n\n");
    
    // Virtual memory gradient (optional, using purple if available)
    if let Some(purple) = theme.get_color("purple") {
        output.push_str("# Virtual memory gradient\n");
        output.push_str("[virtual_start] = \"");
        output.push_str(purple);
        output.push_str("\"\n");
        output.push_str("[virtual_mid] = \"");
        if let Some(lightened) = lighten_color(purple, 0.2) {
            output.push_str(&lightened);
        } else {
            output.push_str(purple);
        }
        output.push_str("\"\n");
        output.push_str("[virtual_end] = \"");
        output.push_str(purple);
        output.push_str("\"\n");
    }
    
    Ok(output)
}
