use anyhow::Result;
use crate::theme::Theme;

pub fn generate(theme: &Theme) -> Result<String> {
    let mut output = String::new();
    
    output.push_str("# Fastfetch theme: ");
    output.push_str(&theme.name);
    output.push_str("\n");
    output.push_str("# Generated by themectl\n\n");
    
    output.push_str("colorTitle=\"");
    if let Some(orange) = theme.get_color("orange") {
        output.push_str(orange);
    } else {
        output.push_str(&theme.colors.accent);
    }
    output.push_str("\"\n");
    output.push_str("colorDefault=\"");
    output.push_str(&theme.colors.fg);
    output.push_str("\"\n");
    output.push_str("colorSeparator=\"");
    if let Some(gray) = theme.get_color("gray") {
        output.push_str(gray);
    } else {
        output.push_str(&theme.colors.cyan);
    }
    output.push_str("\"\n");
    if let Some(purple) = theme.get_color("purple") {
        output.push_str("colorKeys=\"");
        output.push_str(purple);
        output.push_str("\"\n");
    }
    
    Ok(output)
}
