use anyhow::Result;
use crate::theme::Theme;
use crate::utils::hex_to_rgb;

/// Convert hex color to closest Git color name
/// Git supports: normal, black, red, green, yellow, blue, magenta, cyan, white
fn hex_to_git_color(hex: &str) -> &'static str {
    if let Some((r, g, b)) = hex_to_rgb(hex) {
        // Calculate brightness
        let brightness = (r as f32 * 0.299 + g as f32 * 0.587 + b as f32 * 0.114) / 255.0;
        
        // For very dark colors, use black
        if brightness < 0.1 {
            return "black";
        }
        
        // For very light colors, use white
        if brightness > 0.9 {
            return "white";
        }
        
        // Find dominant color channel
        let max = r.max(g.max(b));
        let min = r.min(g.min(b));
        let delta = max - min;
        
        if delta < 30 {
            // Grayscale
            if brightness > 0.5 {
                "white"
            } else {
                "black"
            }
        } else if max == r {
            if g > b {
                if r > 200 && g > 150 {
                    "yellow"
                } else {
                    "red"
                }
            } else {
                "red"
            }
        } else if max == g {
            if r > b {
                if g > 200 && r > 150 {
                    "yellow"
                } else {
                    "green"
                }
            } else {
                "green"
            }
        } else {
            // max == b
            if r > g {
                if b > 200 && r > 150 {
                    "magenta"
                } else {
                    "blue"
                }
            } else if g > 150 {
                "cyan"
            } else {
                "blue"
            }
        }
    } else {
        "normal"
    }
}

pub fn generate(theme: &Theme) -> Result<String> {
    let mut output = String::new();
    
    output.push_str("# Git color configuration: ");
    output.push_str(&theme.name);
    output.push_str("\n");
    output.push_str("# Generated by themectl\n");
    output.push_str("# Add this to your ~/.gitconfig file or use: git config --global --add include.path ~/.config/git/themes/");
    output.push_str(&theme.name);
    output.push_str(".conf\n\n");
    
    // Enable color UI
    output.push_str("[color]\n");
    output.push_str("    ui = auto\n\n");
    
    // Diff colors
    output.push_str("[color \"diff\"]\n");
    output.push_str("    meta = ");
    output.push_str(hex_to_git_color(&theme.colors.yellow));
    output.push_str(" bold\n");
    output.push_str("    frag = ");
    output.push_str(hex_to_git_color(&theme.colors.magenta));
    output.push_str(" bold\n");
    output.push_str("    old = ");
    output.push_str(hex_to_git_color(&theme.colors.red));
    output.push_str(" bold\n");
    output.push_str("    new = ");
    output.push_str(hex_to_git_color(&theme.colors.green));
    output.push_str(" bold\n");
    output.push_str("    whitespace = ");
    output.push_str(hex_to_git_color(&theme.colors.red));
    output.push_str(" reverse\n");
    output.push_str("    commit = ");
    output.push_str(hex_to_git_color(&theme.colors.cyan));
    output.push_str(" bold\n");
    output.push_str("    func = ");
    output.push_str(hex_to_git_color(&theme.colors.blue));
    output.push_str(" bold\n\n");
    
    // Branch colors
    output.push_str("[color \"branch\"]\n");
    output.push_str("    current = ");
    output.push_str(hex_to_git_color(&theme.colors.yellow));
    output.push_str(" reverse\n");
    output.push_str("    local = ");
    output.push_str(hex_to_git_color(&theme.colors.yellow));
    output.push_str("\n");
    output.push_str("    remote = ");
    output.push_str(hex_to_git_color(&theme.colors.green));
    output.push_str("\n");
    output.push_str("    upstream = ");
    output.push_str(hex_to_git_color(&theme.colors.cyan));
    output.push_str("\n");
    output.push_str("    plain = ");
    output.push_str(hex_to_git_color(&theme.colors.fg));
    output.push_str("\n\n");
    
    // Status colors
    output.push_str("[color \"status\"]\n");
    output.push_str("    added = ");
    output.push_str(hex_to_git_color(&theme.colors.green));
    output.push_str(" bold\n");
    output.push_str("    changed = ");
    output.push_str(hex_to_git_color(&theme.colors.yellow));
    output.push_str(" bold\n");
    output.push_str("    untracked = ");
    output.push_str(hex_to_git_color(&theme.colors.red));
    output.push_str("\n");
    output.push_str("    deleted = ");
    output.push_str(hex_to_git_color(&theme.colors.red));
    output.push_str(" bold\n");
    output.push_str("    branch = ");
    output.push_str(hex_to_git_color(&theme.colors.cyan));
    output.push_str(" bold\n");
    output.push_str("    header = ");
    output.push_str(hex_to_git_color(&theme.colors.accent));
    output.push_str(" bold\n");
    output.push_str("    nobranch = ");
    output.push_str(hex_to_git_color(&theme.colors.red));
    output.push_str("\n\n");
    
    // Interactive colors (for git add -p, etc.)
    output.push_str("[color \"interactive\"]\n");
    output.push_str("    prompt = ");
    output.push_str(hex_to_git_color(&theme.colors.accent));
    output.push_str(" bold\n");
    output.push_str("    header = ");
    output.push_str(hex_to_git_color(&theme.colors.cyan));
    output.push_str(" bold\n");
    output.push_str("    help = ");
    output.push_str(hex_to_git_color(&theme.colors.yellow));
    output.push_str(" bold\n");
    output.push_str("    error = ");
    output.push_str(hex_to_git_color(&theme.colors.red));
    output.push_str(" bold\n");
    output.push_str("    reset = normal\n\n");
    
    // Grep colors (for git grep)
    output.push_str("[color \"grep\"]\n");
    output.push_str("    match = ");
    output.push_str(hex_to_git_color(&theme.colors.yellow));
    output.push_str(" bold\n");
    output.push_str("    context = ");
    output.push_str(hex_to_git_color(&theme.colors.fg));
    output.push_str("\n");
    output.push_str("    filename = ");
    output.push_str(hex_to_git_color(&theme.colors.cyan));
    output.push_str(" bold\n");
    output.push_str("    function = ");
    output.push_str(hex_to_git_color(&theme.colors.blue));
    output.push_str(" bold\n");
    output.push_str("    lineNumber = ");
    output.push_str(hex_to_git_color(&theme.colors.magenta));
    output.push_str(" bold\n");
    output.push_str("    column = ");
    output.push_str(hex_to_git_color(&theme.colors.blue));
    output.push_str(" bold\n");
    output.push_str("    selected = ");
    output.push_str(hex_to_git_color(&theme.colors.accent));
    output.push_str(" reverse\n");
    output.push_str("    separator = ");
    output.push_str(hex_to_git_color(&theme.colors.fg));
    output.push_str("\n");
    
    Ok(output)
}

/// Generate Home Manager-compatible Nix code for Git color configuration
pub fn generate_nix(theme: &Theme) -> Result<String> {
    let mut output = String::new();
    
    output.push_str("# Git color configuration for Home Manager: ");
    output.push_str(&theme.name);
    output.push_str("\n");
    output.push_str("# Generated by themectl\n");
    output.push_str("# Add this to your Home Manager configuration:\n");
    output.push_str("#   programs.git.extraConfig = ");
    output.push_str(&theme.name);
    output.push_str("GitColors;\n\n");
    
    output.push_str("let\n");
    output.push_str("  ");
    output.push_str(&theme.name);
    output.push_str("GitColors = {\n");
    
    // Color UI
    output.push_str("    color.ui = \"auto\";\n\n");
    
    // Diff colors
    output.push_str("    \"color.diff.meta\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.yellow));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.diff.frag\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.magenta));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.diff.old\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.red));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.diff.new\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.green));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.diff.whitespace\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.red));
    output.push_str(" reverse\";\n");
    output.push_str("    \"color.diff.commit\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.cyan));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.diff.func\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.blue));
    output.push_str(" bold\";\n\n");
    
    // Branch colors
    output.push_str("    \"color.branch.current\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.yellow));
    output.push_str(" reverse\";\n");
    output.push_str("    \"color.branch.local\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.yellow));
    output.push_str("\";\n");
    output.push_str("    \"color.branch.remote\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.green));
    output.push_str("\";\n");
    output.push_str("    \"color.branch.upstream\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.cyan));
    output.push_str("\";\n");
    output.push_str("    \"color.branch.plain\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.fg));
    output.push_str("\";\n\n");
    
    // Status colors
    output.push_str("    \"color.status.added\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.green));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.status.changed\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.yellow));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.status.untracked\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.red));
    output.push_str("\";\n");
    output.push_str("    \"color.status.deleted\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.red));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.status.branch\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.cyan));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.status.header\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.accent));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.status.nobranch\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.red));
    output.push_str("\";\n\n");
    
    // Interactive colors
    output.push_str("    \"color.interactive.prompt\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.accent));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.interactive.header\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.cyan));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.interactive.help\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.yellow));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.interactive.error\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.red));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.interactive.reset\" = \"normal\";\n\n");
    
    // Grep colors
    output.push_str("    \"color.grep.match\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.yellow));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.grep.context\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.fg));
    output.push_str("\";\n");
    output.push_str("    \"color.grep.filename\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.cyan));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.grep.function\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.blue));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.grep.lineNumber\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.magenta));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.grep.column\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.blue));
    output.push_str(" bold\";\n");
    output.push_str("    \"color.grep.selected\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.accent));
    output.push_str(" reverse\";\n");
    output.push_str("    \"color.grep.separator\" = \"");
    output.push_str(hex_to_git_color(&theme.colors.fg));
    output.push_str("\";\n");
    
    output.push_str("  };\n");
    output.push_str("in\n");
    output.push_str("  {\n");
    output.push_str("    programs.git = {\n");
    output.push_str("      enable = true;\n");
    output.push_str("      extraConfig = ");
    output.push_str(&theme.name);
    output.push_str("GitColors;\n");
    output.push_str("    };\n");
    output.push_str("  }\n");
    
    Ok(output)
}
