use anyhow::Result;
use crate::theme::Theme;
use crate::utils::hex_to_rgb;

pub fn generate(theme: &Theme) -> Result<String> {
    let mut output = String::new();
    
    output.push_str("# Hyprpaper theme: ");
    output.push_str(&theme.name);
    output.push_str("\n");
    output.push_str("# Generated by themectl\n\n");
    
    // Default wallpaper path (user should customize this)
    // The path can be set per theme in the theme properties or via environment
    output.push_str("# Default wallpaper for this theme\n");
    output.push_str("# Replace with your wallpaper path\n");
    output.push_str("# Example: preload = ~/Pictures/wallpapers/");
    output.push_str(&theme.name);
    output.push_str(".jpg\n");
    output.push_str("preload = \n\n");
    
    output.push_str("# Set wallpaper for all outputs\n");
    output.push_str("# Format: wallpaper = OUTPUT,/path/to/wallpaper\n");
    output.push_str("# Use empty OUTPUT (,) to set for all outputs\n");
    output.push_str("wallpaper = ,\n\n");
    
    // Wallpaper tinting/filtering
    // Hyprpaper doesn't have built-in tinting, but we can use hyprshade or suggest tinted wallpapers
    output.push_str("# Wallpaper Tinting/Filtering\n");
    output.push_str("# Hyprpaper doesn't support direct color tinting, but you can:\n");
    output.push_str("# 1. Use hyprshade for color overlays:\n");
    output.push_str("#    hyprshade on <shader-name>\n");
    output.push_str("# 2. Pre-process wallpapers with theme colors\n");
    output.push_str("# 3. Use a compositor shader for color adjustment\n\n");
    
    // Theme color reference for wallpaper selection
    output.push_str("# Theme Color Reference (for wallpaper selection/filtering)\n");
    output.push_str("# Use these colors when selecting or processing wallpapers:\n");
    output.push_str("# Background: ");
    output.push_str(&theme.colors.bg);
    output.push_str("\n");
    output.push_str("# Foreground: ");
    output.push_str(&theme.colors.fg);
    output.push_str("\n");
    output.push_str("# Accent: ");
    output.push_str(&theme.colors.accent);
    output.push_str("\n");
    
    // RGB values for potential shader/tinting scripts
    if let Some((r, g, b)) = hex_to_rgb(&theme.colors.bg) {
        output.push_str("# Background RGB: ");
        output.push_str(&format!("{} {} {}", r, g, b));
        output.push_str("\n");
    }
    if let Some((r, g, b)) = hex_to_rgb(&theme.colors.accent) {
        output.push_str("# Accent RGB: ");
        output.push_str(&format!("{} {} {}", r, g, b));
        output.push_str("\n");
    }
    
    output.push_str("\n# Example: Apply subtle tint using theme accent color\n");
    output.push_str("# You can create a script that applies a color overlay to wallpapers\n");
    output.push_str("# using imagemagick or similar tools with the theme colors above\n");
    
    Ok(output)
}
