use anyhow::Result;
use crate::theme::Theme;
use crate::utils::hex_to_rgb;

pub fn generate(theme: &Theme) -> Result<String> {
    let mut output = String::new();
    
    output.push_str("# Hyprland theme: ");
    output.push_str(&theme.name);
    output.push_str("\n");
    output.push_str("# Generated by themectl\n\n");
    
    // Border width
    if let Some(border_width) = theme.properties.border_width {
        output.push_str(&format!("general:border_size = {}\n", border_width));
    }
    
    // Shadow blur
    if let Some(shadow_blur) = theme.properties.shadow_blur {
        output.push_str(&format!("decoration:shadow_size = {}\n", shadow_blur));
    }
    
    output.push_str("\n");
    
    // Active border color with alpha
    if let Some((r, g, b)) = hex_to_rgb(&theme.colors.accent) {
        output.push_str("col.active_border = rgba(");
        output.push_str(&format!("{} {} {} 0.8", r, g, b));
        output.push_str(")\n");
    }
    
    // Inactive border color with alpha
    if let Some((r, g, b)) = hex_to_rgb(&theme.colors.bg) {
        output.push_str("col.inactive_border = rgba(");
        output.push_str(&format!("{} {} {} 0.5", r, g, b));
        output.push_str(")\n");
    }
    
    // Shadow color with alpha
    if let Some((r, g, b)) = hex_to_rgb(&theme.colors.bg) {
        output.push_str("col.shadow = rgba(");
        output.push_str(&format!("{} {} {} 0.3", r, g, b));
        output.push_str(")\n");
    }
    
    Ok(output)
}
