use anyhow::Result;
use crate::theme::Theme;

pub fn generate(theme: &Theme) -> Result<String> {
    let mut output = String::new();
    
    output.push_str("# Mako theme: ");
    output.push_str(&theme.name);
    output.push_str("\n");
    output.push_str("# Generated by themectl\n\n");
    
    output.push_str("background-color=");
    output.push_str(&theme.colors.bg);
    output.push_str("\n");
    output.push_str("border-color=");
    output.push_str(&theme.colors.accent);
    output.push_str("\n");
    output.push_str("text-color=");
    output.push_str(&theme.colors.fg);
    output.push_str("\n\n");
    
    output.push_str("# Urgency levels\n");
    output.push_str("[urgency=low]\n");
    if let Some(purple) = theme.get_color("purple") {
        output.push_str("border-color=");
        output.push_str(purple);
        output.push_str("\n");
    } else {
        output.push_str("border-color=");
        output.push_str(&theme.colors.cyan);
        output.push_str("\n");
    }
    output.push_str("\n");
    
    output.push_str("[urgency=normal]\n");
    output.push_str("border-color=");
    output.push_str(&theme.colors.accent);
    output.push_str("\n\n");
    
    // Warning level (if orange is available)
    if let Some(orange) = theme.get_color("orange") {
        output.push_str("[urgency=warning]\n");
        output.push_str("border-color=");
        output.push_str(orange);
        output.push_str("\n");
        output.push_str("text-color=");
        output.push_str(orange);
        output.push_str("\n\n");
    }
    
    output.push_str("[urgency=critical]\n");
    output.push_str("border-color=");
    output.push_str(&theme.colors.red);
    output.push_str("\n");
    output.push_str("background-color=");
    output.push_str(&theme.colors.red);
    output.push_str("\n");
    output.push_str("text-color=");
    output.push_str(&theme.colors.bg);
    output.push_str("\n");
    
    Ok(output)
}
