use anyhow::Result;
use crate::theme::Theme;
use crate::utils::{lighten_color, dim_color};

pub fn generate(theme: &Theme) -> Result<String> {
    let mut output = String::new();
    
    output.push_str("-- Neovim colorscheme: ");
    output.push_str(&theme.name);
    output.push_str("\n");
    output.push_str("-- Generated by themectl\n\n");
    
    output.push_str("local colors = {\n");
    output.push_str("  bg = \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\",\n");
    output.push_str("  fg = \"");
    output.push_str(&theme.colors.fg);
    output.push_str("\",\n");
    output.push_str("  accent = \"");
    output.push_str(&theme.colors.accent);
    output.push_str("\",\n");
    output.push_str("  red = \"");
    output.push_str(&theme.colors.red);
    output.push_str("\",\n");
    output.push_str("  green = \"");
    output.push_str(&theme.colors.green);
    output.push_str("\",\n");
    output.push_str("  yellow = \"");
    output.push_str(&theme.colors.yellow);
    output.push_str("\",\n");
    output.push_str("  blue = \"");
    output.push_str(&theme.colors.blue);
    output.push_str("\",\n");
    output.push_str("  magenta = \"");
    output.push_str(&theme.colors.magenta);
    output.push_str("\",\n");
    output.push_str("  cyan = \"");
    output.push_str(&theme.colors.cyan);
    output.push_str("\",\n");
    if let Some(orange) = theme.get_color("orange") {
        output.push_str("  orange = \"");
        output.push_str(orange);
        output.push_str("\",\n");
    }
    if let Some(purple) = theme.get_color("purple") {
        output.push_str("  purple = \"");
        output.push_str(purple);
        output.push_str("\",\n");
    }
    if let Some(pink) = theme.get_color("pink") {
        output.push_str("  pink = \"");
        output.push_str(pink);
        output.push_str("\",\n");
    }
    if let Some(white) = theme.get_color("white") {
        output.push_str("  white = \"");
        output.push_str(white);
        output.push_str("\",\n");
    }
    if let Some(black) = theme.get_color("black") {
        output.push_str("  black = \"");
        output.push_str(black);
        output.push_str("\",\n");
    }
    if let Some(gray) = theme.get_color("gray") {
        output.push_str("  gray = \"");
        output.push_str(gray);
        output.push_str("\",\n");
    }
    output.push_str("}\n\n");
    
    let bg_light = if let Some(gray) = theme.get_color("gray") {
        gray.to_string()
    } else {
        lighten_color(&theme.colors.bg, 0.05).unwrap_or_else(|| theme.colors.bg.clone())
    };
    let fg_dim = if let Some(gray) = theme.get_color("gray") {
        gray.to_string()
    } else {
        dim_color(&theme.colors.fg, 0.6).unwrap_or_else(|| theme.colors.fg.clone())
    };
    
    output.push_str("local bg_light = \"");
    output.push_str(&bg_light);
    output.push_str("\"\n");
    output.push_str("local fg_dim = \"");
    output.push_str(&fg_dim);
    output.push_str("\"\n\n");
    
    output.push_str("vim.cmd(\"hi clear\")\n");
    output.push_str("if vim.fn.exists(\"syntax_on\") then\n");
    output.push_str("  vim.cmd(\"syntax reset\")\n");
    output.push_str("end\n\n");
    
    output.push_str("vim.g.colors_name = \"");
    output.push_str(&theme.name);
    output.push_str("\"\n\n");
    
    // Normal mode
    output.push_str("vim.api.nvim_set_hl(0, \"Normal\", { bg = colors.bg, fg = colors.fg })\n");
    output.push_str("vim.api.nvim_set_hl(0, \"CursorLine\", { bg = bg_light })\n");
    
    // Visual selection
    output.push_str("vim.api.nvim_set_hl(0, \"Visual\", { bg = colors.accent, fg = colors.bg })\n");
    
    // Line numbers
    output.push_str("vim.api.nvim_set_hl(0, \"LineNr\", { fg = fg_dim })\n");
    output.push_str("vim.api.nvim_set_hl(0, \"CursorLineNr\", { fg = colors.accent })\n");
    
    // Status line
    output.push_str("vim.api.nvim_set_hl(0, \"StatusLine\", { bg = colors.accent, fg = colors.bg })\n");
    output.push_str("vim.api.nvim_set_hl(0, \"StatusLineNC\", { bg = bg_light, fg = colors.fg })\n");
    
    // Comments
    if let Some(gray) = theme.get_color("gray") {
        output.push_str(&format!("vim.api.nvim_set_hl(0, \"Comment\", {{ fg = \"{}\" }})\n", gray));
    } else {
        output.push_str("vim.api.nvim_set_hl(0, \"Comment\", { fg = fg_dim })\n");
    }
    
    // Syntax highlighting
    output.push_str("vim.api.nvim_set_hl(0, \"String\", { fg = colors.green })\n");
    output.push_str("vim.api.nvim_set_hl(0, \"Keyword\", { fg = colors.blue })\n");
    output.push_str("vim.api.nvim_set_hl(0, \"Function\", { fg = colors.cyan })\n");
    output.push_str("vim.api.nvim_set_hl(0, \"Type\", { fg = colors.yellow })\n");
    if let Some(_) = theme.get_color("purple") {
        output.push_str("vim.api.nvim_set_hl(0, \"Constant\", { fg = colors.purple })\n");
    } else {
        output.push_str("vim.api.nvim_set_hl(0, \"Constant\", { fg = colors.magenta })\n");
    }
    output.push_str("vim.api.nvim_set_hl(0, \"Statement\", { fg = colors.blue })\n");
    if let Some(_) = theme.get_color("purple") {
        output.push_str("vim.api.nvim_set_hl(0, \"PreProc\", { fg = colors.purple })\n");
    } else {
        output.push_str("vim.api.nvim_set_hl(0, \"PreProc\", { fg = colors.magenta })\n");
    }
    if let Some(_) = theme.get_color("pink") {
        output.push_str("vim.api.nvim_set_hl(0, \"Special\", { fg = colors.pink })\n");
    } else {
        output.push_str("vim.api.nvim_set_hl(0, \"Special\", { fg = colors.cyan })\n");
    }
    if let Some(_) = theme.get_color("purple") {
        output.push_str("vim.api.nvim_set_hl(0, \"Number\", { fg = colors.purple })\n");
    } else {
        output.push_str("vim.api.nvim_set_hl(0, \"Number\", { fg = colors.magenta })\n");
    }
    output.push_str("vim.api.nvim_set_hl(0, \"Boolean\", { fg = colors.blue })\n");
    if let Some(_) = theme.get_color("orange") {
        output.push_str("vim.api.nvim_set_hl(0, \"Todo\", { fg = colors.orange })\n");
        output.push_str("vim.api.nvim_set_hl(0, \"Tag\", { fg = colors.orange })\n");
    }
    
    // Errors and warnings
    output.push_str("vim.api.nvim_set_hl(0, \"Error\", { fg = colors.red })\n");
    output.push_str("vim.api.nvim_set_hl(0, \"WarningMsg\", { fg = colors.yellow })\n");
    
    // Diagnostics
    output.push_str("vim.api.nvim_set_hl(0, \"DiagnosticError\", { fg = colors.red })\n");
    output.push_str("vim.api.nvim_set_hl(0, \"DiagnosticWarn\", { fg = colors.yellow })\n");
    output.push_str("vim.api.nvim_set_hl(0, \"DiagnosticInfo\", { fg = colors.blue })\n");
    output.push_str("vim.api.nvim_set_hl(0, \"DiagnosticHint\", { fg = colors.cyan })\n");
    
    // Diff
    output.push_str("vim.api.nvim_set_hl(0, \"DiffAdd\", { fg = colors.green })\n");
    output.push_str("vim.api.nvim_set_hl(0, \"DiffDelete\", { fg = colors.red })\n");
    output.push_str("vim.api.nvim_set_hl(0, \"DiffChange\", { fg = colors.yellow })\n");
    output.push_str("vim.api.nvim_set_hl(0, \"DiffText\", { fg = colors.blue })\n");
    
    // Search
    output.push_str("vim.api.nvim_set_hl(0, \"Search\", { bg = colors.yellow, fg = colors.bg })\n");
    output.push_str("vim.api.nvim_set_hl(0, \"IncSearch\", { bg = colors.accent, fg = colors.bg })\n");
    
    // Completion menu
    output.push_str("vim.api.nvim_set_hl(0, \"Pmenu\", { bg = bg_light, fg = colors.fg })\n");
    output.push_str("vim.api.nvim_set_hl(0, \"PmenuSel\", { bg = colors.accent, fg = colors.bg })\n");
    
    // Folds
    output.push_str("vim.api.nvim_set_hl(0, \"Folded\", { fg = fg_dim })\n");
    
    Ok(output)
}
