use anyhow::Result;
use crate::theme::Theme;
use crate::generators;

pub fn generate(theme: &Theme) -> Result<String> {
    let mut output = String::new();
    
    output.push_str("# Theme: ");
    output.push_str(&theme.name);
    output.push_str("\n");
    if !theme.description.is_empty() {
        output.push_str("# ");
        output.push_str(&theme.description);
        output.push_str("\n");
    }
    output.push_str("\n");
    
    output.push_str("{\n");
    output.push_str("  bg = \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\";\n");
    output.push_str("  fg = \"");
    output.push_str(&theme.colors.fg);
    output.push_str("\";\n");
    output.push_str("  accent = \"");
    output.push_str(&theme.colors.accent);
    output.push_str("\";\n");
    output.push_str("  red = \"");
    output.push_str(&theme.colors.red);
    output.push_str("\";\n");
    output.push_str("  green = \"");
    output.push_str(&theme.colors.green);
    output.push_str("\";\n");
    output.push_str("  yellow = \"");
    output.push_str(&theme.colors.yellow);
    output.push_str("\";\n");
    output.push_str("  blue = \"");
    output.push_str(&theme.colors.blue);
    output.push_str("\";\n");
    output.push_str("  magenta = \"");
    output.push_str(&theme.colors.magenta);
    output.push_str("\";\n");
    output.push_str("  cyan = \"");
    output.push_str(&theme.colors.cyan);
    output.push_str("\";\n");
    
    if let Some(orange) = theme.get_color("orange") {
        output.push_str("  orange = \"");
        output.push_str(orange);
        output.push_str("\";\n");
    }
    if let Some(purple) = theme.get_color("purple") {
        output.push_str("  purple = \"");
        output.push_str(purple);
        output.push_str("\";\n");
    }
    if let Some(pink) = theme.get_color("pink") {
        output.push_str("  pink = \"");
        output.push_str(pink);
        output.push_str("\";\n");
    }
    if let Some(white) = theme.get_color("white") {
        output.push_str("  white = \"");
        output.push_str(white);
        output.push_str("\";\n");
    }
    if let Some(black) = theme.get_color("black") {
        output.push_str("  black = \"");
        output.push_str(black);
        output.push_str("\";\n");
    }
    if let Some(gray) = theme.get_color("gray") {
        output.push_str("  gray = \"");
        output.push_str(gray);
        output.push_str("\";\n");
    }
    
    output.push_str("}\n");
    
    Ok(output)
}

/// Generate a Home Manager module for a specific application
pub fn generate_home_manager_module(theme: &Theme, app: &str) -> Result<String> {
    let mut output = String::new();
    
    // Module header
    output.push_str("# Home Manager module for ");
    output.push_str(app);
    output.push_str(" theme configuration\n");
    output.push_str("# Generated by themectl\n");
    output.push_str("# Theme: ");
    output.push_str(&theme.name);
    output.push_str("\n");
    if !theme.description.is_empty() {
        output.push_str("# ");
        output.push_str(&theme.description);
        output.push_str("\n");
    }
    output.push_str("\n");
    
    // Generate the actual config content for this app
    let config_content = generators::generate(theme, app)?;
    
    // Create module based on application type
    match app {
        "kitty" => {
            output.push_str("{ config, lib, pkgs, ... }:\n\n");
            output.push_str("{\n");
            output.push_str("  programs.kitty = {\n");
            output.push_str("    enable = true;\n");
            output.push_str("    settings = {\n");
            // Parse kitty config and convert to Nix format
            // For now, use extraConfig to embed the generated config
            output.push_str("      extraConfig = ''\n");
            for line in config_content.lines() {
                output.push_str("        ");
                output.push_str(line);
                output.push_str("\n");
            }
            output.push_str("      '';\n");
            output.push_str("    };\n");
            output.push_str("  };\n");
            output.push_str("}\n");
        }
        "waybar" => {
            output.push_str("{ config, lib, pkgs, ... }:\n\n");
            output.push_str("{\n");
            output.push_str("  programs.waybar = {\n");
            output.push_str("    enable = true;\n");
            output.push_str("    style = ''\n");
            for line in config_content.lines() {
                output.push_str("      ");
                output.push_str(line);
                output.push_str("\n");
            }
            output.push_str("    '';\n");
            output.push_str("  };\n");
            output.push_str("}\n");
        }
        "starship" => {
            output.push_str("{ config, lib, pkgs, ... }:\n\n");
            output.push_str("{\n");
            output.push_str("  programs.starship = {\n");
            output.push_str("    enable = true;\n");
            // Parse TOML and convert to Nix
            output.push_str("    settings = lib.importTOML (pkgs.writeText \"starship.toml\" ''\n");
            for line in config_content.lines() {
                output.push_str("      ");
                output.push_str(line);
                output.push_str("\n");
            }
            output.push_str("    '');\n");
            output.push_str("  };\n");
            output.push_str("}\n");
        }
        "neovim" => {
            output.push_str("{ config, lib, pkgs, ... }:\n\n");
            output.push_str("{\n");
            output.push_str("  programs.neovim = {\n");
            output.push_str("    enable = true;\n");
            output.push_str("    extraLuaConfig = ''\n");
            for line in config_content.lines() {
                output.push_str("      ");
                output.push_str(line);
                output.push_str("\n");
            }
            output.push_str("    '';\n");
            output.push_str("  };\n");
            output.push_str("}\n");
        }
        "mako" => {
            output.push_str("{ config, lib, pkgs, ... }:\n\n");
            output.push_str("{\n");
            output.push_str("  services.mako = {\n");
            output.push_str("    enable = true;\n");
            // Parse config format and convert
            output.push_str("    extraConfig = ''\n");
            for line in config_content.lines() {
                output.push_str("      ");
                output.push_str(line);
                output.push_str("\n");
            }
            output.push_str("    '';\n");
            output.push_str("  };\n");
            output.push_str("}\n");
        }
        "hyprland" => {
            output.push_str("{ config, lib, pkgs, ... }:\n\n");
            output.push_str("{\n");
            output.push_str("  wayland.windowManager.hyprland = {\n");
            output.push_str("    enable = true;\n");
            output.push_str("    extraConfig = ''\n");
            for line in config_content.lines() {
                output.push_str("      ");
                output.push_str(line);
                output.push_str("\n");
            }
            output.push_str("    '';\n");
            output.push_str("  };\n");
            output.push_str("}\n");
        }
        "wofi" | "wlogout" => {
            output.push_str("{ config, lib, pkgs, ... }:\n\n");
            output.push_str("{\n");
            output.push_str("  home.file.\".config/");
            output.push_str(app);
            output.push_str("/style.css\".text = ''\n");
            for line in config_content.lines() {
                output.push_str("    ");
                output.push_str(line);
                output.push_str("\n");
            }
            output.push_str("  '';\n");
            output.push_str("}\n");
        }
        "fastfetch" => {
            output.push_str("{ config, lib, pkgs, ... }:\n\n");
            output.push_str("{\n");
            output.push_str("  home.file.\".config/fastfetch/config.jsonc\".text = ''\n");
            for line in config_content.lines() {
                output.push_str("    ");
                output.push_str(line);
                output.push_str("\n");
            }
            output.push_str("  '';\n");
            output.push_str("}\n");
        }
        "yazi" => {
            output.push_str("{ config, lib, pkgs, ... }:\n\n");
            output.push_str("{\n");
            output.push_str("  home.file.\".config/yazi/yazi.toml\".text = ''\n");
            for line in config_content.lines() {
                output.push_str("    ");
                output.push_str(line);
                output.push_str("\n");
            }
            output.push_str("  '';\n");
            output.push_str("}\n");
        }
        "hyprpaper" => {
            output.push_str("{ config, lib, pkgs, ... }:\n\n");
            output.push_str("{\n");
            output.push_str("  home.file.\".config/hypr/hyprpaper.conf\".text = ''\n");
            for line in config_content.lines() {
                output.push_str("    ");
                output.push_str(line);
                output.push_str("\n");
            }
            output.push_str("  '';\n");
            output.push_str("}\n");
        }
        "gtk" => {
            output.push_str("{ config, lib, pkgs, ... }:\n\n");
            output.push_str("{\n");
            output.push_str("  home.file.\".config/gtk-4.0/settings.ini\".text = ''\n");
            for line in config_content.lines() {
                output.push_str("    ");
                output.push_str(line);
                output.push_str("\n");
            }
            output.push_str("  '';\n");
            output.push_str("}\n");
        }
        "btop" => {
            output.push_str("{ config, lib, pkgs, ... }:\n\n");
            output.push_str("{\n");
            output.push_str("  home.file.\".config/btop/themes/");
            output.push_str(&theme.name);
            output.push_str(".theme\".text = ''\n");
            for line in config_content.lines() {
                output.push_str("    ");
                output.push_str(line);
                output.push_str("\n");
            }
            output.push_str("  '';\n");
            output.push_str("}\n");
        }
        "git" => {
            output.push_str("{ config, lib, pkgs, ... }:\n\n");
            output.push_str("{\n");
            output.push_str("  programs.git = {\n");
            output.push_str("    enable = true;\n");
            output.push_str("    extraConfig = ''\n");
            for line in config_content.lines() {
                output.push_str("      ");
                output.push_str(line);
                output.push_str("\n");
            }
            output.push_str("    '';\n");
            output.push_str("  };\n");
            output.push_str("}\n");
        }
        _ => {
            // Generic fallback - use home.file
            output.push_str("{ config, lib, pkgs, ... }:\n\n");
            output.push_str("{\n");
            output.push_str("  home.file.\".config/");
            output.push_str(app);
            output.push_str("/config\".text = ''\n");
            for line in config_content.lines() {
                output.push_str("    ");
                output.push_str(line);
                output.push_str("\n");
            }
            output.push_str("  '';\n");
            output.push_str("}\n");
        }
    }
    
    Ok(output)
}
