use anyhow::Result;
use crate::theme::Theme;

pub fn generate(theme: &Theme) -> Result<String> {
    let mut output = String::new();
    
    output.push_str("# Starship theme: ");
    output.push_str(&theme.name);
    output.push_str("\n");
    output.push_str("# Generated by themectl\n\n");
    
    output.push_str("[palette]\n");
    output.push_str("orange = \"");
    output.push_str(theme.get_color("orange")
        .or_else(|| theme.get_color("accent"))
        .unwrap_or("#fe8019"));
    output.push_str("\"\n");
    output.push_str("yellow = \"");
    output.push_str(theme.get_color("yellow").unwrap_or("#d79921"));
    output.push_str("\"\n");
    output.push_str("aqua = \"");
    output.push_str(theme.get_color("cyan").unwrap_or("#689d6a"));
    output.push_str("\"\n");
    output.push_str("blue = \"");
    output.push_str(theme.get_color("blue").unwrap_or("#458588"));
    output.push_str("\"\n");
    output.push_str("green = \"");
    output.push_str(theme.get_color("green").unwrap_or("#98971a"));
    output.push_str("\"\n");
    output.push_str("red = \"");
    output.push_str(theme.get_color("red").unwrap_or("#cc241d"));
    output.push_str("\"\n");
    output.push_str("purple = \"");
    output.push_str(theme.get_color("purple")
        .or_else(|| theme.get_color("magenta"))
        .unwrap_or("#b16286"));
    output.push_str("\"\n\n");
    
    output.push_str("[format]\n");
    output.push_str("all = \"$all\"\n\n");
    
    output.push_str("[palettes]\n");
    output.push_str("default = { bg1 = \"");
    let bg = theme.get_color("bg").unwrap_or("#282828");
    output.push_str(bg);
    output.push_str("\", bg3 = \"");
    if let Some(lightened) = crate::utils::lighten_color(bg, 0.1) {
        output.push_str(&lightened);
    } else {
        output.push_str(bg);
    }
    output.push_str("\", fg0 = \"");
    output.push_str(theme.get_color("fg").unwrap_or("#ebdbb2"));
    output.push_str("\" }\n");
    
    Ok(output)
}
