use anyhow::Result;
use crate::theme::Theme;
use crate::utils::darken_color;

pub fn generate(theme: &Theme) -> Result<String> {
    let mut output = String::new();
    
    let border_radius = theme.properties.border_radius.unwrap_or(0);
    let border_width = theme.properties.border_width.unwrap_or(2);
    let spacing = theme.properties.spacing.unwrap_or(8);
    
    output.push_str("# Wlogout theme: ");
    output.push_str(&theme.name);
    output.push_str("\n");
    output.push_str("# Generated by themectl\n\n");
    
    output.push_str("window {\n");
    output.push_str("  background-color: ");
    output.push_str(&theme.colors.bg);
    output.push_str(";\n");
    output.push_str(&format!("  border: {}px solid ", border_width));
    output.push_str(&theme.colors.accent);
    output.push_str(";\n");
    if border_radius > 0 {
        output.push_str(&format!("  border-radius: {}px;\n", border_radius));
    }
    output.push_str("}\n\n");
    
    output.push_str("button {\n");
    output.push_str("  color: ");
    output.push_str(&theme.colors.fg);
    output.push_str(";\n");
    output.push_str("  background-color: ");
    output.push_str(&theme.colors.bg);
    output.push_str(";\n");
    output.push_str(&format!("  border: {}px solid ", border_width / 2));
    if let Some(darkened) = darken_color(&theme.colors.accent, 0.2) {
        output.push_str(&darkened);
    } else {
        output.push_str(&theme.colors.accent);
    }
    output.push_str(";\n");
    if border_radius > 0 {
        output.push_str(&format!("  border-radius: {}px;\n", border_radius));
    }
    output.push_str(&format!("  padding: {}px;\n", spacing));
    output.push_str("}\n\n");
    
    output.push_str("button:hover {\n");
    output.push_str("  background-color: ");
    output.push_str(&theme.colors.accent);
    output.push_str(";\n");
    output.push_str("  color: ");
    output.push_str(&theme.colors.bg);
    output.push_str(";\n");
    output.push_str("}\n");
    
    Ok(output)
}
