use anyhow::Result;
use crate::theme::Theme;
use crate::utils::darken_color;

pub fn generate(theme: &Theme) -> Result<String> {
    let mut output = String::new();
    
    output.push_str("# Yazi theme: ");
    output.push_str(&theme.name);
    output.push_str("\n");
    output.push_str("# Generated by themectl\n\n");
    
    // Manager section - UI colors
    output.push_str("[manager]\n");
    output.push_str("# Cwd (current working directory)\n");
    output.push_str("cwd = [\"");
    output.push_str(&theme.colors.fg);
    output.push_str("\"]\n\n");
    
    output.push_str("# Hovered\n");
    output.push_str("hovered = [\"");
    if let Some(orange) = theme.get_color("orange") {
        output.push_str(orange);
    } else {
        output.push_str(&theme.colors.accent);
    }
    output.push_str("\", \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\"]\n\n");
    
    output.push_str("# Find (search)\n");
    output.push_str("find_keyword = [\"");
    output.push_str(&theme.colors.yellow);
    output.push_str("\", \"bold\"]\n");
    output.push_str("find_position = [\"");
    output.push_str(&theme.colors.accent);
    output.push_str("\", \"bold\", \"underline\"]\n\n");
    
    output.push_str("# Marker (selection)\n");
    output.push_str("marker_copied = [\"");
    output.push_str(&theme.colors.green);
    output.push_str("\", \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\"]\n");
    output.push_str("marker_cut = [\"");
    output.push_str(&theme.colors.red);
    output.push_str("\", \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\"]\n");
    output.push_str("marker_selected = [\"");
    if let Some(purple) = theme.get_color("purple") {
        output.push_str(purple);
    } else {
        output.push_str(&theme.colors.accent);
    }
    output.push_str("\", \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\"]\n\n");
    
    // Tab section
    output.push_str("[manager.tab]\n");
    output.push_str("# Active tab\n");
    output.push_str("active = [\"");
    output.push_str(&theme.colors.bg);
    output.push_str("\", \"");
    output.push_str(&theme.colors.accent);
    output.push_str("\"]\n");
    output.push_str("# Inactive tab\n");
    output.push_str("inactive = [\"");
    if let Some(gray) = theme.get_color("gray") {
        output.push_str(gray);
    } else if let Some(dimmed) = darken_color(&theme.colors.fg, 0.4) {
        output.push_str(&dimmed);
    } else {
        output.push_str(&theme.colors.fg);
    }
    output.push_str("\", \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\"]\n\n");
    
    // Status section
    output.push_str("[status]\n");
    output.push_str("# Status bar background\n");
    output.push_str("separator_open = [\"");
    output.push_str(&theme.colors.accent);
    output.push_str("\", \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\"]\n");
    output.push_str("separator_close = [\"");
    output.push_str(&theme.colors.accent);
    output.push_str("\", \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\"]\n");
    output.push_str("# Status bar text\n");
    output.push_str("code = [\"");
    if let Some(white) = theme.get_color("white") {
        output.push_str(white);
    } else {
        output.push_str(&theme.colors.fg);
    }
    output.push_str("\", \"");
    if let Some(black) = theme.get_color("black") {
        output.push_str(black);
    } else {
        output.push_str(&theme.colors.bg);
    }
    output.push_str("\"]\n");
    output.push_str("# Status bar info\n");
    output.push_str("info = [\"");
    output.push_str(&theme.colors.cyan);
    output.push_str("\", \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\"]\n");
    output.push_str("# Status bar warning\n");
    output.push_str("warn = [\"");
    output.push_str(&theme.colors.yellow);
    output.push_str("\", \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\"]\n");
    output.push_str("# Status bar error\n");
    output.push_str("error = [\"");
    output.push_str(&theme.colors.red);
    output.push_str("\", \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\"]\n\n");
    
    // Tasks section
    output.push_str("[tasks]\n");
    output.push_str("# Task bar background\n");
    output.push_str("border = \"");
    output.push_str(&theme.colors.accent);
    output.push_str("\"\n");
    output.push_str("# Task bar title\n");
    output.push_str("title = \"");
    output.push_str(&theme.colors.fg);
    output.push_str("\"\n");
    output.push_str("# Task bar percentage\n");
    output.push_str("percentage = \"");
    output.push_str(&theme.colors.cyan);
    output.push_str("\"\n");
    output.push_str("# Task bar partial\n");
    output.push_str("partial = \"");
    output.push_str(&theme.colors.accent);
    output.push_str("\"\n\n");
    
    // Notify section
    output.push_str("[notify]\n");
    output.push_str("# Notification title\n");
    output.push_str("title = \"");
    output.push_str(&theme.colors.fg);
    output.push_str("\"\n");
    output.push_str("# Notification info\n");
    output.push_str("info = \"");
    output.push_str(&theme.colors.cyan);
    output.push_str("\"\n");
    output.push_str("# Notification warning\n");
    output.push_str("warn = \"");
    output.push_str(&theme.colors.yellow);
    output.push_str("\"\n");
    output.push_str("# Notification error\n");
    output.push_str("error = \"");
    output.push_str(&theme.colors.red);
    output.push_str("\"\n\n");
    
    // Input section
    output.push_str("[input]\n");
    output.push_str("# Input border\n");
    output.push_str("border = \"");
    output.push_str(&theme.colors.accent);
    output.push_str("\"\n");
    output.push_str("# Input title\n");
    output.push_str("title = \"");
    output.push_str(&theme.colors.fg);
    output.push_str("\"\n");
    output.push_str("# Input value\n");
    output.push_str("value = \"");
    output.push_str(&theme.colors.fg);
    output.push_str("\"\n");
    output.push_str("# Input selected\n");
    output.push_str("selected = [\"");
    output.push_str(&theme.colors.accent);
    output.push_str("\", \"reverse\"]\n\n");
    
    // Select section
    output.push_str("[select]\n");
    output.push_str("# Select border\n");
    output.push_str("border = \"");
    output.push_str(&theme.colors.accent);
    output.push_str("\"\n");
    output.push_str("# Select active\n");
    output.push_str("active = [\"");
    output.push_str(&theme.colors.accent);
    output.push_str("\", \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\"]\n");
    output.push_str("# Select inactive\n");
    output.push_str("inactive = [\"");
    output.push_str(&theme.colors.fg);
    output.push_str("\", \"");
    output.push_str(&theme.colors.bg);
    output.push_str("\"]\n");
    
    Ok(output)
}
